name: Post Suite Runner

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  check_suite:
    types:
      - completed

jobs:
  dump:
    runs-on: ubuntu-20.04
    name: Dump context

    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'

      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
        
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'

      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'

  success:
    runs-on: ubuntu-20.04
    name: Success
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Run on success
        run: echo 'Success'

      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'

  labelled:
    runs-on: ubuntu-20.04
    name: With Label
    if: github.event.workflow_run.conclusion == 'success' && github.event.label.name == 'deployment'

    steps:
      - name: Run on success with label
        run: echo 'Success with label'

      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'
